# -*- coding: utf-8 -*-
"""IMAGE_ENRYPTION USING 3 DES.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RBYxkRhs2IZHMPjbJFLBZk0ZfoDiR8e7

**IMAGE SECURITY SYSTEM FOR ARMY, POLICE & SECURE COMMUNICATION**

**IMAGE ENCRYPTION & DECRYPTION USING TRIPLE DES**

**LOAD LIBRARIES**
"""

# Commented out IPython magic to ensure Python compatibility.
# %pylab inline
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import io
!pip install pyDes
from pyDes import *

"""DEFINE FUNCTION"""

# Function to Display Image
def imgdis(path):
  """
  Function to display an image.
  Parameter : Path of image file
  """
  img = mpimg.imread(path)
  imgplot = plt.imshow(img)
  plt.show()

"""ENCRYPTION USING TRIPLE DES"""

# Function to Encrypt an File with Triple DES
def encrypt(key, path, output = 'Encrypted'):
  """
  Function to Encrypt an File with Triple DES

  Parameters :  path, key, output;

  Key  : Takes a Key for the Encryption Process.
  Path : Takes Absolute or Relative Path of File as Input.
  Output : Takes Absolute or Relative Path of File as Output.

  Returns : An Encrypted File.
  """









"""WAIT !!!


---



Project Code is longer it involves many step for Encryption and 
Decryption for Image. 

It's Top Class Projects.


---



## Mail me at **vatshayan007@gmail.com** for Full Project Code with Project Report and PPT

Mail me for any kind of Help in Projects.

# Mail me at **vatshayan007@gmail.com** Now for Projects
"""

